# YOUR PROJECT TITLE

> **Note the following:** 
> 1. This is *not* meant to be an example of an actual **data analysis project**, just an example of how to structure such a project.
> 1. Remember the general advice on structuring and commenting your code
> 1. The `dataproject.py` file includes a function which can be used multiple times in this notebook.

Imports and set magics:

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from matplotlib_venn import venn2

# autoreload modules when code is run
%load_ext autoreload
%autoreload 2

# user written modules
import dataproject


# Read and clean data

Import your data, either through an API or manually, and load it. 

First we import the data to

In [52]:
LorenzData = "Indkomst Data.xlsx" #First we import the data
LData = pd.read_excel(LorenzData, skiprows=2) #Shorten the call for the data
LData.drop("Unnamed: 0", axis=1, inplace=True) #Removing first unnamed column
LData.rename(columns = {"Unnamed: 1":"Decil"}, inplace=True) #Renaming first column

LData = LData.dropna() #Removes missing values from bottom rows
LData.iloc[:, 1:] = LData.iloc[:, 1:].astype(int) #Removing decimal points from all numbers using iloc to locate numbers

LData


[2010. 2011. 2012. 2013. 2014. 2015. 2016. 2017. 2018. 2019. 2020. 2021.]


C:\Users\bjorn\AppData\Local\Temp\ipykernel_7136\1243367800.py:10: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  LData.iloc[:, 1:] = LData.iloc[:, 1:].astype(int)


Decil    2010    2011    2012    2013    2014    2015    2016    2017  \
0   1. decil   58517   61405   72143   75689   70459   77728   75853   78128   
1   2. decil  133314  135247  138299  140042  142148  143630  144500  146503   
2   3. decil  155258  157641  160792  163578  166795  169095  171292  174947   
3   4. decil  176861  179613  182871  185928  190010  192715  195643  200087   
4   5. decil  198711  202048  205633  209382  214412  217580  221437  226804   
5   6. decil  220835  224771  228906  233521  239499  243288  248126  254422   
6   7. decil  245061  249659  254534  260358  267373  271974  277775  285080   
7   8. decil  274629  280171  285933  293589  301774  307454  314207  322842   
8   9. decil  318054  325162  332513  342856  352557  360069  368072  378649   
9  10. decil  500012  516944  533189  560971  573866  607665  615554  641188   

     2018    2019    2020    2021  
0   78721   83792   88188   95473  
1  151039  154985  160361  166971  
2  179714  184053  190111  196935  
3  205721  210708  218820  227383  
4  233247  238796  249210  259036  
5  261607  267917  280604  291453  
6  293222  300200  315119  327257  
7  331975  339935  357273  371556  
8  388934  398818  419353  437776  
9  648231  688377  719999  779827

## Explore each data set

In [76]:
Years = np.linspace(2010,2021,num=12) #Creating a list of numbers ranging from 2010-2021
Years_int = Years.astype(int) #Converting the list variables from float to integers
print(Years)

#Using for loop to calculate the cummulitative income for each year
for i in Years_int:
    Col_name = "Cum_" + str(i) #Looping over the names for the new columns
    LData[Col_name] = LData[str(i)].cumsum() #Calculating the cummulitative income

LData    
    

[2010. 2011. 2012. 2013. 2014. 2015. 2016. 2017. 2018. 2019. 2020. 2021.]


Decil    2010    2011    2012    2013    2014    2015    2016    2017  \
0   1. decil   58517   61405   72143   75689   70459   77728   75853   78128   
1   2. decil  133314  135247  138299  140042  142148  143630  144500  146503   
2   3. decil  155258  157641  160792  163578  166795  169095  171292  174947   
3   4. decil  176861  179613  182871  185928  190010  192715  195643  200087   
4   5. decil  198711  202048  205633  209382  214412  217580  221437  226804   
5   6. decil  220835  224771  228906  233521  239499  243288  248126  254422   
6   7. decil  245061  249659  254534  260358  267373  271974  277775  285080   
7   8. decil  274629  280171  285933  293589  301774  307454  314207  322842   
8   9. decil  318054  325162  332513  342856  352557  360069  368072  378649   
9  10. decil  500012  516944  533189  560971  573866  607665  615554  641188   

     2018  ...  Cum_2012  Cum_2013  Cum_2014  Cum_2015  Cum_2016  Cum_2017  \
0   78721  ...     72143     75689     70459     77728     75853     78128   
1  151039  ...    210442    215731    212607    221358    220353    224631   
2  179714  ...    371234    379309    379402    390453    391645    399578   
3  205721  ...    554105    565237    569412    583168    587288    599665   
4  233247  ...    759738    774619    783824    800748    808725    826469   
5  261607  ...    988644   1008140   1023323   1044036   1056851   1080891   
6  293222  ...   1243178   1268498   1290696   1316010   1334626   1365971   
7  331975  ...   1529111   1562087   1592470   1623464   1648833   1688813   
8  388934  ...   1861624   1904943   1945027   1983533   2016905   2067462   
9  648231  ...   2394813   2465914   2518893   2591198   2632459   2708650   

   Cum_2018  Cum_2019  Cum_2020  Cum_2021  
0     78721     83792     88188     95473  
1    229760    238777    248549    262444  
2    409474    422830    438660    459379  
3    615195    633538    657480    686762  
4    848442    872334    906690    945798  
5   1110049   1140251   1187294   1237251  
6   1403271   1440451   1502413   1564508  
7   1735246   1780386   1859686   1936064  
8   2124180   2179204   2279039   2373840  
9   2772411   2867581   2999038   3153667  

[10 rows x 25 columns]

In [ ]:
Decile_Num = np.linspace(0,100,num=11)
Decile_Num_Int = Decile_Num.astype(int)
print(Decile_Num)

LData = LData.append(pd.Series(Decile_Num, index=LData.columns), ignore_index=True)

#LData["Cum_Decile"] = LData["Decile_Num_Int"].cumsum()

LData



[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


ValueError: Length of values (11) does not match length of index (25)

Der skal tilføjes en række af nuller i vores datasæt som erstatning for "0.decil"
Kummulitativ deciler skal beregnes 
Procentvis kummulitativ indkomst skal beregnes
Plot Lorenz

In order to be able to **explore the raw data**, you may provide **static** and **interactive plots** to show important developments 

Explain what you see when moving elements of the interactive plot around. 

# Merge data sets

Now you create combinations of your loaded data sets. Remember the illustration of a (inner) **merge**:

Here we are dropping elements from both data set X and data set Y. A left join would keep all observations in data X intact and subset only from Y. 

Make sure that your resulting data sets have the correct number of rows and columns. That is, be clear about which observations are thrown away. 

**Note:** Don't make Venn diagrams in your own data project. It is just for exposition. 

# Analysis

To get a quick overview of the data, we show some **summary statistics** on a meaningful aggregation. 

MAKE FURTHER ANALYSIS. EXPLAIN THE CODE BRIEFLY AND SUMMARIZE THE RESULTS.

# Conclusion

ADD CONCISE CONLUSION.